### ISSUE TITLE
ياخشىمۇ سىز قانداق ئەھۋالىڭىز؟

### ISSUE THREAD

**Issue by new786786** [ishirkhan/shirkhan-alphabet#2]
پايزوندا يىزىلغان ئوچۇق كودىنى تەمىنلىيەلەسىزمۇ؟

**Comment by SilvaQ** [comment]
پايسۇندا بۇنى ئىشلىتىپ مەزمۇن ئايلاندۇرۇش مەخسىتىگە يەتمەكچى بولسىڭىز 
shirkhan
ئىسىملىك پايسىن ئامبىرىنىڭ كودىغا قاراڭ. شۇنداقلا مەزكۇر تۈر نودې جىئەستە ئىشلەيدۇ. شۇنى ئىشلىتىپ مەخسىتىڭىزگە يەتسىڭىز ياكى پايسوندا شۇنى توۋلاپ ئىشلەتسىڭىز بولىدۇ.
تور بەت ۋە nodejs نى ئاساس قىلغان بولغاچقا باشقا تىللاردا قايتا يېزىشنىڭ ھاجىتى يىتەرلىك ئەمەس. پەقەتلا مەزمۇن ئالماشتۇرۇش مەخسەت بولسا  str replace يىتەرلىك.

**Comment by new786786** [comment]
ياخشىمۇ سىز 
مەن ئىلگىرى ئاۋاز بىرىكتۇرۇش تىخنىكىسنى گىتتىكى ئوچۇق كودتىن پايدىلنىپ سىنىغانتىم ..يەنى ئۇيغۇرچە خەتنى ئىنگىلىز تىلدىكى ھەرىپلەردىن پايدىلنىپلا ئوزگەرتىپ ئىپادىلەپ مەشىقلەندۇرۇپ سىنىغانتىم
باشتا ئىنچىكە رايۇنلارغا دىقققەت قىلماپتىمەن ...مەشىقلەندۇرۇپ ئۇنۇم چىققاندىن كىيىن قارىسام بەزى ئۇيغۇرچە خەتنى ئوقۇتسام ئەمدى تىلى چىققان كىچىك بالىدەك ئوقۇۋاتىدۇ.
سەۋەبى ئۇيغۇرچە خەتنى ئالماشتۇرغان ۋاقتىمدا پەقەت 
ASCII 
دىكى 26 ھەرىپتىن باشقا يەنە يۇنىكود رايۇندىكى 3 ھەرىپ قوشۇلۇپ قالغان شۇنىڭ بىلەن مەن ئىشلەتكەن ئوچۇق كود قوشۇلۇپ قالغان 3 ھەرىپنى سۇزۋىتىپتۇ
شۇڭا مۇشۇ ئەھۋال كىپ چىقىپتۇ..بۇ ھەرخىل ئالماشتۇرۇش توغۇرسىدىمۇ ماتىريال خىلى كۆپكەن ئاددىيسى ھەرىپلەرنى چوڭ كىچىك يىزىپمۇ ئالماشتۇرغان ئەھۋال باركەن
ھەممىسنى سىناپ بولدۇم ئۇنۇمى تازا كۆڭۇلدىكىدەك ئەمەس يەنىلا مەشىقلەنگەندىن كىيىن بەزى ھەرىپنى ئىنىق چىقرالمىغان ئەھۋاللار بار شۇڭا سىزنىڭكىدەك بىر ئالماشتۇرۇپ 
سىناپ باقاي دىۋىدىم

**Comment by SilvaQ** [comment]
pip install shirkhan
from shirkhan import ug2shirkhan, shirkhan2ug

 ugword = "xxx"
khanword = ug2shirkhan(ugword)

ugword == shirkhan2ug(khanword)

**Comment by SilvaQ** [comment]
库还提供了get_u_words方法从文本中提取母语单词给你使用。
from shirkhan import get_u_words
get_u_words(ugTexthere)

**Comment by new786786** [comment]
كۆپ رەخمەت بۇرادەر

**Comment by new786786** [comment]
مەشىقلەندۇرۇپ بولۇپ ئۇنىمى چىسقا بۇ ئورۇنغا يوللايمەن

**Comment by new786786** [comment]
from shirkhan import ug2shirkhan, shirkhan2ug
ugword = "ئالما شىركىتى خىزمەتچىلىرىنىڭ ئىش تاشلىشى يەنە ئەۋجىگە چىقتى"
khanword = ug2shirkhan(ugword)
print(khanword)
 

Traceback (most recent call last):
  File "E:/ai_ai/uyasr/shirhan.py", line 3, in <module>
    khanword = ug2shirkhan(ugword)
  File "C:\Users\Administrator\Desktop\py\py3.7\lib\site-packages\shirkhan\shir_shirkhan_alphabet.py", line 124, in ug2shirkhan
    return ShirkhanConverter(word).toShirkhan()
  File "C:\Users\Administrator\Desktop\py\py3.7\lib\site-packages\shirkhan\shir_shirkhan_alphabet.py", line 93, in toShirkhan
    return "".join([ShirkhanAlphabet.alpha_info(alpha)[3] for alpha in word])
  File "C:\Users\Administrator\Desktop\py\py3.7\lib\site-packages\shirkhan\shir_shirkhan_alphabet.py", line 93, in <listcomp>
    return "".join([ShirkhanAlphabet.alpha_info(alpha)[3] for alpha in word])
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by new786786** [comment]
from shirkhan import ug2shirkhan, shirkhan2ug
ugword = "چىقتى"
khanword = ug2shirkhan(ugword)
print(khanword)

ĉiqti

Process finished with exit code 0

**Comment by new786786** [comment]
چىقتى
ĉiqti
يۇنىكود
